spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://insta-clone.cfja5qw9ndkn.ap-northeast-2.rds.amazonaws.com:3306/insta?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: instadev!
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true